# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{unix_epoch}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chetan Sarva"]
  s.date = %q{2011-03-26}
  s.description = %q{Adds from_unix_ts and to_unix_ts methods to the DateTime class}
  s.email = %q{chetan@pixelcop.net}
  s.files = [
    "VERSION",
    "lib/unix_epoch.rb"
  ]
  s.homepage = %q{http://github.com/chetan/unix_epoch}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Adds methods to DateTime for dealing with Unix Timestamps}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

